### ISSUE TITLE
ncbi error

### ISSUE THREAD

**Issue by ghost** [ivan-krukov/DETECT#3]
This happens in the middle of needle process:

Error: (117.2) CThread::Wrapper: CThread::Main() failed
NCBI C++ Exception:
    Error: (CSeqDBException::eArgErr) Sequence not returned.

Error: (117.2) CThread::Wrapper: CThread::Main() failed
NCBI C++ Exception:
    Error: (CSeqDBException::eArgErr) Sequence not returned.

**Comment by ivan-krukov** [comment]
Try this standalone alignment
I had it running with [needle 6.4.0](ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.4.0.tar.gz)
`needle -asequence kinase.fasta -bsequence kinase.fasta -gapopen 10 -gapextend 0.5 -aformat_outfile score -stdout -auto`
